create table user_details(user_id int  generated by default as identity(start with 10 increment by 1 ) primary key,
                          name varchar2(30) not null,
                          email_id varchar2(100) unique not null,
                          password varchar2(15) not null,
                          address varchar2(50),
                          mobile_number number);
                                             


create table inventory(flower_id varchar2(50),
flower_Description varchar2(100),
Flower_name varchar2(50),
color varchar2(50),
retail_price number,
category_name varchar2(50),
primary key(flower_id));

create table orders










